#! /usr/bin/bash



#...play audio in terminal
mpv --ytdl-format=bestaudio+bestvideo --no-config --slang=en ytdl://ytsearch:"$song_name"
# zenity --progress && \
# zenity --text-info --filename=temp.txt --width=800 --height=600


