#!/bin/bash

# Show Zenity dialog with input field and list of options
input_result=$(zenity --forms --title="Play a YouTube video" --text="Enter the search term and the video quality.\nDefault quality will be 360p." \
    --add-entry="Video:" \
    --add-combo="Quality:" --combo-values="144|240|360|480|720|1080" \
    --cancel-label="Cancel")

# Check if user clicked "Cancel" or closed the dialog
if [[ $? -eq 1 ]]; then
  exit
fi

# Extract input and option values
search_for=$(echo "$input_result" | awk -F'|' '{print $1}')
quality=$(echo "$input_result" | awk -F'|' '{print $2}')


echo 'input_result' $input_result
echo 'input_value' $input_value
if [ -z $search_for ]; then
    # Show error message using Zenity
    zenity --error --text="Please input a title."
    exit 1
elif [ -z $quality ]; then
    # Set default option value
    quality=360
fi
# Check if option value is empty

# Display input and option values
echo "Input: $search_for"
echo "Option: $quality"



# #Setting default quality to 480p
# quality=480


mpv --ytdl-format=bestvideo[height"<=$quality"]+bestaudio --slang="en, auto" ytdl://ytsearch:"$search_for" --osc=yes
