#! /usr/bin/bash
        

#Moving to the Music Directory, where these commands will be executed to download file(s) in that directory
init_dir=$(pwd)
cd /mnt/Cave/Home/Music


#Taking the inputs for URLs (if, needed), and other parameters
echo
echo '____________________________'
echo "You're now in the Music Directory"
echo
echo 'Enter the URL of the playlist: '
read url
cat /home/ankit/bash/functions/assets/'file formats'.txt
echo
echo 'Select any quality from the above listed ones, and enter that no. below: '
echo '___________________________________________________________________________'
echo
echo 'The quality of song: '
read quality
echo 'Download from this video of the Playlist: '
read start
echo 'To this video no.: '
read end



#executing the yt-dlp script to download the file(s)
yt-dlp -f $quality -x --audio-format mp3 --verbose --yes-playlist --output "YouTube Playlists/%(playlist_title)s/%(title)s.%(ext)s" --playlist-start $start --playlist-end $end $url --sponsorblock-remove default



#returning to the original repository the user was in at the beginning
cd $init_dir
echo
echo '____________________________'
echo "Welcome back to the directory where you started"
echo

