#!/bin/bash

# Specify the parent folder
parent_folder=$(pwd)

# Loop through each subfolder
for subfolder in "$parent_folder"/*; do
    if [ -d "$subfolder" ]; then
        # Move all files from the subfolder to the parent folder
        mv "$subfolder"/* "$parent_folder"
    fi
done
