#! /usr/bin/bash

high_quality=720



flags="-f "ba+bv[height<="$quality"]" --progress --embed-subs --write-auto-sub --embed-chapters --merge-output-format mkv --output "%\(playlist_title\)s/%\(playlist_index\)s. %\(title\)s.%\(ext\)s" --sponsorblock-remove default"
init_dir=$(pwd)
course_dir='/mnt/Cave/Home/Videos/Courses'






if [ -d "$course_dir" ]; then
	cd $course_dir
else 
	mkdir $course_dir
	cd $course_dir
fi
echo "You're now in the Directory $(pwd)"

#Taking the inputs for URLs (if, needed), and other parameters
echo
echo '____________________________'
url=$(xclip -selection clipboard -o)
echo "The link is taken from the clipboard and that is $url"
echo


#if video number start and end are not specified, set start to 1 and end to 1
if [ -z $start ]; then
	start=1
fi
if [ -z $end ]; then
	end=$start
	echo
	echo "Only $start number video of the given playlist will be downloaded"
	echo
fi

echo "The quality of video(eg. 360, 720 etc. If you press Enter, it will be set to $high_quality): "
read quality

if [ -z $quality ]; then
	quality=$high_quality
	echo "Since you pressed Enter, downloaded quality will be less than or equal to $high_quality"
fi



#Donwnloading the video with the set parameters
yt-dlp $flags $url


