#! /usr/bin/bash

google-chrome-stable --new-window --profile-directory="Profile 1" --start-fullscreen https://seek.onlinedegree.iitm.ac.in/courses/ns_23t2_cs2003?id=2&type=lesson&tab=courses&ann=6584079877144576 &
sleep 1 &&
mpv /mnt/Cave/IITMOD/"MAD I"/Videos



