#! /usr/bin/bash

high_quality=720

echo "Note : You are using the script to download the Video lectures. Though you'll be prompted to enter video quality, if you don't enter anything it will be set to $high_quality. Even if you provide the link of a video from a playlist whole playlist can be downloaded"


init_dir=$(pwd)

course_dir='/mnt/Cave/Home/Videos/Courses'

if [ -d "$course_dir" ]; then
	cd $course_dir
else 
	mkdir $course_dir
	cd $course_dir
fi
echo "You're now in the Directory $(pwd)"

#Taking the inputs for URLs (if, needed), and other parameters
echo
echo '____________________________'
url=$(xclip -selection clipboard -o)
echo "The link is taken from the clipboard and that is $url"
echo


echo
echo '___________________________________________________________________________'
echo
echo 'Download from this video of the Playlist: '
read start
echo 'To this video no.: '
read end

#if video number start and end are not specified, set start to 1 and end to 1
if [ -z $start ]; then
	start=1
fi
if [ -z $end ]; then
	end=$start
	echo
	echo "Only $start number video of the given playlist will be downloaded"
	echo
fi
	
	

echo "The quality of video(eg. 360, 720 etc. If you press Enter, it will be set to $high_quality): "
read quality

if [ -z $quality ]; then
	quality=$high_quality
	echo "Since you pressed Enter, downloaded quality will be less than or equal to $high_quality"
fi






#Donwnloading the video with the set parameters
yt-dlp -f "ba+bv[height<="$quality"]" --progress --embed-subs --write-auto-sub --embed-chapters --merge-output-format mkv --output "%(playlist_title)s/%(playlist_index)s. %(title)s.%(ext)s" --sponsorblock-remove default --playlist-start $start --playlist-end $end $url


#executing the yt-dlp script to download the file(s) also asking the url
#echo 'The quality of video(Height of the video.. eg 360, 720 etc): '
#read quality
#yt-dlp -f ba+bv[height="$quality"] --progress --embed-subs --embed-chapters --merge-output-format mkv --output "%(playlist_title)s/%(playlist_index)s. %(title)s.%(ext)s" --sponsorblock-remove default --playlist-start $start --playlist-end $end $url



#returning to the original repository the user was in at the beginning
cd $init_dir
echo
echo '____________________________'
echo "Welcome back to the directory where you started"
echo

