#! /usr/bin/bash


song_name=$(zenity --entry --text="Which song: ")

#...play audio in terminal
mpv --ytdl-format=bestaudio --slang=en ytdl://ytsearch:"$song_name" |\
zenity --progress && \
zenity --text-info --filename=temp.txt --width=800 --height=600

